title: Andre Gomes
email: andre@cocoon.build
description: Documenting my stuff because I've learn from others' documentation.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://andrelgomes.com"
github_username:  gomesac

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - github-pages
theme: minima
show_excerpts: true
header_pages: 
  - blog.html
  - projects.html
minima:
    social_links:
      github: gomesac
      twitter: andregomes426
      instagram: _blasian_young_adult

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

collections:
  projects:
    output: true

defaults:
  - scope:
     path: ""
     type: "projects"
    values:
      layout: "project"
  - scope:
     path: ""
     type: "posts"
    values:
      layout: "post"
  - scope:
     path: ""
    values:
      layout: "default"
