title: Andre Gomes
email: andre@cocoonfirm.com
description: >- # this means to ignore newlines until "baseurl:"
  Personal site for Andre Gomes
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  gomesac

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - github-pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

collections:
  projects:
    output: true

defaults:
  - scope:
     path: ""
     type: "projects"
    values:
      layout: "project"
  - scope:
     path: ""
     type: "posts"
    values:
      layout: "post"
  - scope:
     path: ""
    values:
      layout: "default"
